name: test_new
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.45.0+445

environment:
  sdk: ">=3.0.0 <4.0.0"
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  retrofit: ^4.9.2
  flutter_bloc: ^9.1.1
  simple_animations: ^5.2.0
  equatable: ^2.0.8
  lottie: ^3.3.2
  local_auth: ^3.0.0
  webview_flutter: ^4.13.1
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  package_info_plus: ^9.0.0
  dio: ^5.9.1
  dio_cookie_manager: ^3.3.0
  permission_handler: ^12.0.1
  graphql_flutter: ^5.2.1
  graphql: ^5.2.3
  speech_to_text: ^7.3.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  device_info_plus: ^12.3.0
  location: ^8.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  file_saver: ^0.3.1
  floor: ^1.5.0
  connectivity_plus: ^7.0.0
  carousel_slider: ^5.1.1
  double_back_to_close: ^2.0.0
  upgrader: ^12.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_bounce: ^1.1.0
  flutter_material_color_picker: ^1.2.0
  firebase_database: ^12.1.2
  page_transition: ^2.2.1
  flutter_exif_rotation: ^0.5.2
  open_file: ^3.5.11
  overlay_support: ^2.1.0
  flutter_widget_from_html: ^0.17.1
  flutter_polyline_points: ^3.1.0
  html_unescape: ^2.0.0
  fl_chart: ^1.1.1
  unique_simple_bar_chart: ^0.0.4
  countries_world_map: ^1.3.0
  pie_chart: ^5.4.0
  flutter_html: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.0.3
  json_annotation: ^4.9.0
  build_runner: ^2.7.0
  json_serializable: ^6.7.0

dependency_overrides:
  firebase_core_platform_interface: ^6.0.2
  web_socket_channel: ^3.0.3
  connectivity_plus: ^7.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/lottie/
    - assets/responses/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
